  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: todo-ui-deployment
  spec: 
    replicas: 3
    selector: 
      matchExpressions: 
      - key: app
        operator: In
        values: 
        - todo-ui
    strategy: 
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
    template: 
      metadata: 
        labels: 
          app : todo-ui
      spec: 
        containers: 
        - image: subho9407/todo-ui
          name: todo-ui-container
          ports: 
          - containerPort: 80